# Generated by Django 5.1.2 on 2024-10-14 03:27

import banjo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisines', banjo.models.StringField(default='')),
                ('name', banjo.models.StringField(default='')),
                ('ingredients', banjo.models.StringField(default='')),
                ('instructions', banjo.models.StringField(default='')),
                ('likes', banjo.models.IntegerField(default=0)),
                ('views', banjo.models.IntegerField(default=0)),
                ('popularity', banjo.models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
