# Generated by Django 5.1.2 on 2024-10-18 00:45

import banjo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_cuisines_recipe_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_taken',
            field=banjo.models.StringField(default=''),
        ),
    ]
